fix: add "postgres" user password
jembi/platform pull request #195
Opened 2022-12-19 08:27 UTC by IlyesBenAmara

Context: 
- When deploying the platform, @nour-borgi and i stumbled into this error : 
![image](https://user-images.githubusercontent.com/22627035/208378889-0b1f62f1-aab0-4b97-9f82-850907b3a75f.png)
- The [bitnami/postgresql-repmgr:14](https://hub.docker.com/r/bitnami/postgresql-repmgr) image now requires the `postgres` user password. 
![image](https://user-images.githubusercontent.com/22627035/208380677-b6822b51-ba61-42bb-bf37-2af7bd7933fc.png)
Fix: 
- Added `POSTGRESQL_POSTGRES_PASSWORD` env variable to both the client-regitstry-santempi and fhir-datastore-hapi-fhir packages.

2022-12-19 08:53 UTC, nour-borgi approved these changes

2022-12-19 14:53 UTC, michaelloosen requested changes
Nice catch, please make a small modification.

2022-12-19 14:53 UTC, michaelloosen commented on client-registry-santempi/docker-compose-postgres.yml
> +      POSTGRESQL_POSTGRES_PASSWORD: postgres
We should rather have this configurable via an env var and defaulted to this value in the `package-metadata.json` file as I'm sure people won't want to keep this default as their password in production.

2022-12-20 13:23 UTC, michaelloosen approved these changes
LGTM

2022-12-20 13:52 UTC, merged