Plat 606 kafka packages refactor
jembi/platform pull request #196
Opened 2022-12-19 15:27 UTC by nour-borgi

In this PR, I refactored the swarm script of: 
- message bus kafka
- kafka mapper consumer 
- kafka unbundler consumer 

Fixed a problem with displaying the warning multiple times: 
![image](https://user-images.githubusercontent.com/48720958/208445384-df4c73b2-c53d-4d96-9537-7fc218f676d2.png)

to be displayed only once: 
![image](https://user-images.githubusercontent.com/48720958/208455329-8a77df47-ca61-41e9-80f2-4e92bda8e9c1.png)

2023-01-03 09:28 UTC, marrouchi requested changes
I believe the comments should apply across all PRs , wdyt ?

2023-01-03 09:28 UTC, marrouchi commented on kafka-mapper-consumer/swarm.sh
> +  docker::prune_configs "kafka-mapper-consumer"
```suggestion
  docker::prune_configs "$service_name"
```

2023-01-03 09:28 UTC, marrouchi commented on kafka-mapper-consumer/swarm.sh
> +    log error "Failed to deploy Kafka Mapper Consumer package"
```suggestion
    log error "Failed to deploy $service_name package"
```

2023-01-03 09:28 UTC, marrouchi commented on kafka-mapper-consumer/swarm.sh
> +    log info "Running Kafka Mapper Consumer package"
```suggestion
    log info "Running $service_name package"
```

2023-01-03 09:28 UTC, marrouchi commented on kafka-mapper-consumer/swarm.sh
> +    log info "Destroying Kafka Mapper Consumer"
```suggestion
    log info "Destroying $service_name"
```

2023-01-03 09:28 UTC, marrouchi commented on kafka-mapper-consumer/swarm.sh
> +    log info "Scaling down Kafka Mapper Consumer"
```suggestion
    log info "Scaling down $service_name"
```

2023-01-03 10:43 UTC, nour-borgi commented on kafka-mapper-consumer/swarm.sh
> +  docker::prune_configs "kafka-mapper-consumer"
it is config label and not service name

2023-01-03 10:43 UTC, nour-borgi commented on kafka-mapper-consumer/swarm.sh
> +    log error "Failed to deploy Kafka Mapper Consumer package"
done in another PR

2023-01-03 10:43 UTC, nour-borgi commented on kafka-mapper-consumer/swarm.sh
> +    log info "Running Kafka Mapper Consumer package"
done in another PR

2023-01-03 10:43 UTC, nour-borgi commented on kafka-mapper-consumer/swarm.sh
> +    log info "Destroying Kafka Mapper Consumer"
done in another PR

2023-01-03 10:43 UTC, nour-borgi commented on kafka-mapper-consumer/swarm.sh
> +    log info "Scaling down Kafka Mapper Consumer"
done in another PR

2023-01-03 16:27 UTC, marrouchi approved these changes

2023-01-04 08:29 UTC, Mark-Labuschagne approved these changes

2023-01-04 14:30 UTC, merged