Tb 65 tests according files changes
jembi/platform pull request #208
Opened 2023-01-10 15:37 UTC by nour-borgi

2023-01-11 17:31 UTC, marrouchi requested changes
Could we make one extend the other to avoid repetition ?

2023-01-12 10:30 UTC, bradsawadye approved these changes

2023-01-13 14:19 UTC, marrouchi approved these changes

2023-01-13 14:19 UTC, marrouchi commented on analytics-datastore-clickhouse/package-metadata.json
> +    "tests": "test"
Do we need this var ?

2023-01-13 16:29 UTC, marrouchi approved these changes

2023-01-13 16:47 UTC, merged