PLAT-670 Kafka dependent packages to use new Kafka
jembi/platform pull request #220
Opened 2023-02-15 14:50 UTC by Mark-Labuschagne

WIP

2023-02-28 08:11 UTC, nour-borgi commented on client-registry-jempi/docker-compose.kafdrop-dev.yml
> -  jempi-kafdrop:
we need to remove the config importer in the importer folder as well (kafka.js and docker-compose.config.yml)

2023-02-28 08:13 UTC, nour-borgi commented on client-registry-jempi/package-metadata.json
>      "JEMPI_KAFDROP_CPU_LIMIT": "0",
we don't need kafdrop cpu and memory limits anymore

2023-02-28 08:15 UTC, nour-borgi commented on client-registry-jempi/package-metadata.json
>      "JEMPI_KAFKA_TOPICS": "JeMPI-async-preprocessor,JeMPI-patient-controller,JeMPI-patient-em,JeMPI-patient-linker,JeMPI-mu-linker,JeMPI-notifications",
I think this is something we need to care about, maybe we can put all these topics along side with the other topics in kafka folder, and they can be overwritten according to each implementation ?

2023-02-28 08:15 UTC, nour-borgi commented on client-registry-jempi/swarm.sh
>        "${VOLUME_NAMES[@]}"
this can be removed also

2023-02-28 08:16 UTC, nour-borgi commented on client-registry-jempi/swarm.sh
>      "jempi-kafdrop"
kafdrop can be removed also

2023-02-28 08:21 UTC, nour-borgi commented on client-registry-jempi/swarm.sh
> +    log info "Importing JeMPI Kafka topics"
The env vars in docker compose config importer are still configured to "jempi-kafdrop', kafdrop host should be "kafdrop" right ?, also I think we need to add message-bus-kafka as a dependency to this package

2023-03-17 10:18 UTC, michaelloosen requested changes

2023-03-17 10:18 UTC, michaelloosen commented on data-mapper-logstash/docker-compose.yml
> +      KAKFA_HOSTS: ${KAKFA_HOSTS}
KAKFA_HOSTS should be KAFKA_HOSTS

2023-03-22 10:21 UTC, nour-borgi commented on data-mapper-logstash/docker-compose.yml
> +      KAKFA_HOSTS: ${KAKFA_HOSTS}
cool

2023-03-24 10:38 UTC, merged