Plat 693 split configs keycloak
jembi/platform pull request #223
Opened 2023-03-15 16:35 UTC by nour-borgi

2023-03-16 12:06 UTC, bradsawadye approved these changes

2023-03-16 12:35 UTC, michaelloosen requested changes

2023-03-16 12:35 UTC, michaelloosen commented on identity-access-manager-keycloak/package-metadata.json
> +    "KC_GRAFANA_SSO_ENABLED": "true",
I think we should probably have it disabled by default and then have the implementation decide on whether or not the specific integration with KC is required. What do you think?

2023-03-17 10:37 UTC, michaelloosen requested changes

2023-03-17 10:37 UTC, michaelloosen commented on dashboard-visualiser-superset/package-metadata.json
> +    "KC_SUPERSET_SSO_ENABLED": "true",
This default should also be false.
```suggestion
    "KC_SUPERSET_SSO_ENABLED": "false",
```

2023-03-17 13:13 UTC, nour-borgi commented on dashboard-visualiser-superset/package-metadata.json
> +    "KC_SUPERSET_SSO_ENABLED": "true",
done :)

2023-03-22 09:15 UTC, michaelloosen approved these changes

2023-03-22 12:18 UTC, merged