Docker images scanning
jembi/platform pull request #224
Opened 2023-03-28 08:57 UTC by bradsawadye

This is so we are always informed on the vulnerabilities in the images used in the platform toolbox

PLAT-289

2023-04-06 08:40 UTC, nour-borgi approved these changes

2023-04-06 08:59 UTC, michaelloosen requested changes

2023-04-06 08:59 UTC, michaelloosen commented on .github/workflows/docker-image-scan.yml
> +      - name: Run trivy vulnerability scanner for the OpenHIM core image
Are we meant to be checking the core and console images here if they already have their own action notifying us? I assume this action should only do scanning for the platform image itself?

2023-05-08 10:51 UTC, michaelloosen commented
@bradsawadye Can we close this PR?

2023-05-25 10:35 UTC, closed without merging